export const emptyFilm = {
  originalTitle: '',
  englishTitle: '',
  logline: '',
  shortSynopsis: '',
  fullSynopsis: '',
  durationMinutes: '',
  completionDate: '',
  productionCountry: '',
  languages: '',
  form: 'Documentary',
  stage: 'finished',
  premiereStatus: 'none',
  publishedPublicly: false,
  hasEnglishSubtitles: false,
  hasSrt: false,
  screenerUrl: '',
  screenerPassword: '',
  directorName: '',
  directorBio: '',
  directorStatement: '',
  producerName: '',
  producerEmail: '',
  producerPhone: '',
  archiveFilmId: '',
  archiveYear: '',
}

export const emptyState = {
  film: { ...emptyFilm },
  package: {},
  rights: {},
  submissions: [],
}
